workflows:
  build-tao-app:
    name: Tao Diario APK Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.example.tao_diario_app"
    scripts:
      - name: Instalar dependencias
        script: |
          flutter pub get
      - name: Verificar errores
        script: |
          flutter analyze
      - name: Ejecutar pruebas unitarias (si hay)
        script: |
          flutter test || echo "Sin pruebas aún"
      - name: Compilar APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - tuemail@ejemplo.com